### ISSUE TITLE
pdksync:pdk_convert errors on every module

### ISSUE THREAD

**Issue by genebean** [puppetlabs/pdksync#163] opened 2021-09-03 14:07 UTC
## Describe the Bug

I get this for every module in my managed modules list:

```bash
╔ ☕️  beanm1:~/repos/dio-pdksync (main ✘) ✭
╚ᐅ bundle exec rake pdksync:pdk_convert
INFO - PdkSync: ploperations-account,
INFO - PdkSync:

------------Files to be added-----------
/Users/geneliverman/repos/dio-pdksync/modules_pdksync/ploperations-account/hiera.yaml
/Users/geneliverman/repos/dio-pdksync/modules_pdksync/ploperations-account/data/common.yaml

----------Files to be modified----------
/Users/geneliverman/repos/dio-pdksync/modules_pdksync/ploperations-account/metadata.json

----------------------------------------

You can find a report of differences in convert_report.txt.



ERROR - PdkSync: Unable to run command '/opt/puppetlabs/pdk/bin/pdk convert --force --template-url=https://github.com/puppetlabs/pdk-templates.git --template-ref=2.2.0': pdk (FATAL):
/opt/puppetlabs/pdk/private/ruby/2.5.9/bin/ruby: invalid option -:  (-h will show valid options) (RuntimeError)

pdk (FATAL): Unable to resolve Gemfile dependencies.

INFO - PdkSync: converted
```

## Expected Behavior

I expect it to successfully run `pdk convert` on each module.

## Environment
 - Version 0.6.0

**Comment by genebean** [comment] 2021-09-03 14:12
Interestingly, if I run it again I get this:

```bash
╔ ☕️  beanm1:~/repos/dio-pdksync (main ✘) ✭
╚ᐅ bundle exec rake pdksync:pdk_convert
INFO - PdkSync: ploperations-account,
INFO - PdkSync:
No changes required.


INFO - PdkSync: converted
```

It seems as though it must be doing the conversions even though it is throwing errors... this is very confusing.

**Comment by jordanbreen28** [comment] 2023-07-11 11:27
Hey @genebean thanks for raising this.
I went ahead and tried to replicate this using the same module you listed and can't seem to reproduce the issue.
I'm going to vote to close this issue due to its age and the fact I was unable to replicate, but please do re-open it if you find it persists.

**Closed by jordanbreen28** 2023-07-11 11:27 UTC
Labels: bug
